name: Test, Build & Deploy

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]
 
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          node-version: [18.x]
          # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install packages and run tests
        run: | 
          npm install
          npm run test
  deploy:
    if: github.ref == 'refs/heads/dev' && github.event_name != 'pull_request'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Deploy Node Express TypeScript BE
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or Public key of the server
          username: ${{secrets.SSH_USERNAME}} # User of server you want to ssh into
          
          script: |
            echo 'Deployment Successful To Digital Ocean'